package com.arkanoid.gui;

import java.io.BufferedReader;
import com.arkanoid.arkanoidjakubblunar.Hra;
import com.arkanoid.arkanoidjakubblunar.Okno;
import com.arkanoid.arkanoidjakubblunar.Rebricek;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Main frame, ktorý predstavuje hlavné menu hry
 *
 * @author Kubo
 */
public class Main extends javax.swing.JFrame {

    private Okno oknoHry;
    private Hra hra;
    private int hracovMaxLevel;
    private final int maxLevel;

    /**
     * Načíta určený zdroj z jar suboru
     *
     * @param res - cesta k zdroju
     * @return - súbor v jar
     */
    public static File loadResource(String res) {
        try {
            InputStream in = ClassLoader.getSystemClassLoader().getResourceAsStream(res);
            if (in == null) {
                return null;
            }

            File tempFile = File.createTempFile(String.valueOf(in.hashCode()), ".tmp");
            tempFile.deleteOnExit();

            try (FileOutputStream out = new FileOutputStream(tempFile)) {
                byte[] buffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = in.read(buffer)) != -1) {
                    out.write(buffer, 0, bytesRead);
                }
            }
            return tempFile;
        } catch (IOException e) {
            return null;
        }

    }

    /**
     * Vráti maximalný level hráča, ktorý može hráč hrať
     *
     * @return cislo levelu, ktorý je pre hrača najtaší
     */
    public int getHracovMaxLevel() {
        return hracovMaxLevel;
    }

    /**
     * Nastaví maximalny level hráča
     *
     * @param hracovMaxLevel - cislo levelu, ktorý je pre hrača najtaší
     */
    public void setHracovMaxLevel(int hracovMaxLevel) {
        this.hracovMaxLevel = hracovMaxLevel;
        int index = 0;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (int i = 1; i <= maxLevel; i++) {
            if (i > hracovMaxLevel) {
                break;
            } else {
                model.addElement(i + "");
            }

        }
        jComboBoxLevel.setModel(model);
    }

    /**
     * Posledný level hry
     *
     * @return posledný level hry
     */
    public int getMaxLevel() {
        return maxLevel;
    }

    /**
     * Creates new form Main
     */
    public Main() {

        initComponents();
        hracovMaxLevel = 1;
        BufferedReader br;
        File progress = new File("progress");
        try {
            br = new BufferedReader(new InputStreamReader(new FileInputStream(progress), "utf-8"));
            String text = br.readLine();
            int lvl = Integer.parseInt(text);
            hracovMaxLevel = lvl;
        } catch (FileNotFoundException ex) {
            try (Writer writer = new BufferedWriter(new OutputStreamWriter(
                    new FileOutputStream(progress), "utf-8"))) {
                writer.write(1 + "");
                writer.close();
            } catch (IOException ex1) {
                int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Nejde nacitat");
            }

        } catch (IOException ex) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Nejde nacitat");
        }

        int index = 0;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        int pocet = 0;
        File levelyc = Main.loadResource("Levely/config");
        try {
            br = new BufferedReader(new InputStreamReader(new FileInputStream(levelyc), "utf-8"));
            pocet = Integer.parseInt(br.readLine());
            br.close();
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {
        }

        for (int i = 1; i <= pocet; i++) {
            if (i > hracovMaxLevel) {
                break;
            } else {
                model.addElement(i + "");
            }

        }

        maxLevel = pocet;
        jComboBoxLevel.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldMeno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLevel = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Nová hra");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("Top 10");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jTextFieldMeno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMenoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Super Arkanoid");

        jLabel2.setText("Vaše meno:");

        jLabel3.setText("Level:");

        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Koniec");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxLevel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMeno)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed

        String[] options = new String[]{"Späť"};
        JOptionPane.showOptionDialog(null, Rebricek.dajInstanciu().toString(), "Hall of Fame",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[0]);

    }//GEN-LAST:event_jButton2MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        if (jButton1.isEnabled()) {
            String[] options = new String[]{"Áno", "Nie"};
            int vysledok = JOptionPane.showOptionDialog(null, "Začať novú hru?", "",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);

            if (vysledok == 0) {
                Hra.setRozmery(800, 600);
                hra = new Hra((String) jComboBoxLevel.getSelectedItem(), jTextFieldMeno.getText(), this);
                oknoHry = new Okno(800, 600, "", hra);
                Hra.setOkno(oknoHry);
                hra.start();
            }
        }

    }//GEN-LAST:event_jButton1MousePressed

    private void jTextFieldMenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMenoKeyTyped
        if (jTextFieldMeno.getText() != null
                && !jTextFieldMeno.getText().trim().isEmpty()) {
            jButton1.setEnabled(true);
        } else {
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldMenoKeyTyped

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        String[] options = new String[]{"Áno", "Nie"};
        int vysledok = JOptionPane.showOptionDialog(null, "Naozaj chcete skončiť ?", "",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[0]);

        if (vysledok == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldMeno;
    // End of variables declaration//GEN-END:variables
}
